przedszkole/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('rodzina.urls')),
    path('', include('rozliczenie.urls')),
    path('admin/', admin.site.urls),
]

rodzina/urls.py
from django.urls import path, include
from .views import (
    ChildrenListView,
    TutorListView,
    FamilyCreate,
    FamilyListView,
    FamilyUpdate,
    GroupListView,
    GrupUpdate,
    PersonCreate,
    PersonJSON,
    PersonNewAjax,
    PersonUpdate,
    PersonDeleteAjax,
    RFIDDeleteAjax,
    RFIDNewAjax,
)


urlpatterns = [
    path('system/', include('django.contrib.auth.urls')),

    path('children/', ChildrenListView.as_view(), name='children'),
    path('tutor/', TutorListView.as_view(), name='tutor'),

    path('person/new/', PersonCreate.as_view(), name='person_new'),
    path(
        'person/<int:pk>/',
        PersonUpdate.as_view(),
        name='person_edit'),
    path(
        'person/<int:pk>/json/',
        PersonJSON.as_view(),
        name='person_ajax'),
    path(
        'person/new/json/',
        PersonNewAjax.as_view(),
        name='person_new_ajax'),
    path(
        'person/<int:pk>/delete/',
        PersonDeleteAjax.as_view(),
        name='person_delete'),


    path('family/new/', FamilyCreate.as_view(), name='family_new'),
    path('family_list/', FamilyListView.as_view(), name='family_list'),
    path('family/<int:pk>/', FamilyUpdate.as_view(), name='family_edit'),

    path(
        'rfid/<int:pk>/delete/',
        RFIDDeleteAjax.as_view(),
        name='rfid_delete'),

    path(
        'rfid/new/',
        RFIDNewAjax.as_view(),
        name='rfid_new_ajax'
    ),

    path('group_list/', GroupListView.as_view(), name='group_list'),
    path('group/<int:pk>/', GrupUpdate.as_view(), name='group_edit'),
]

rodzina/models.py
from django.db import models


class Group(models.Model):
    name = models.CharField(max_length=100, verbose_name='nazwa')

    class Meta:
        verbose_name = 'Nazwa'
        verbose_name_plural = 'Grupy'

    def __str__(self):
        return f'{self.name}'


class Family(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nazwisko')

    class Meta:
        verbose_name = 'Rodzina'
        verbose_name_plural = 'Rodziny'

    def children_count(self):
        return self.people.filter(type_of_person='C').count()

    def get_children(self):
        return self.people.filter(type_of_person='C')

    def get_tutor(self):
        return self.people.filter(type_of_person='T')

    def __str__(self):
        return f'{self.name}'


class RFID(models.Model):
    rfid_number = models.PositiveIntegerField(
        unique=True, verbose_name='Kod RFID')
    family = models.ForeignKey(
        Family, on_delete=models.CASCADE, related_name='rfids',
        verbose_name='Rodzina')

    def __str__(self):
        return f'{self.rfid_number}'


class Person(models.Model):
    TUTOR = 'T'
    CHILD = 'C'
    TYPE_OF_PERSON = [
        (TUTOR, 'Opiekun'),
        (CHILD, 'Dziecko')
    ]

    first_name = models.CharField(max_length=80, verbose_name='Imię')
    last_name = models.CharField(max_length=100, verbose_name='Nazwisko')
    type_of_person = models.CharField(
        max_length=1, choices=TYPE_OF_PERSON, default=CHILD,
        verbose_name="Rola w rodzinie")
    family = models.ForeignKey(
        Family, on_delete=models.CASCADE, related_name='people',
        verbose_name='Rodzina')
    group = models.ForeignKey(
        Group, on_delete=models.CASCADE, related_name='children',
        blank=True, null=True, verbose_name='Grupa')

    class Meta:
        verbose_name = 'Osoba'
        verbose_name_plural = 'Osoby'

    def __str__(self):
        return f'{self.last_name} {self.first_name} - \
        {self.get_type_of_person_display()} / {self.group}'

rodzina/views.py
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.views.generic.detail import SingleObjectMixin
from django.views import generic, View
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Person, Family, Group, RFID


class ChildrenListView(LoginRequiredMixin, generic.ListView):
    model = Person
    template_name = 'rodzina/children_list.html'
    fields = [
        'first_name',
        'last_name',
        'group',
    ]

    def get_queryset(self):
        return Person.objects.filter(type_of_person='C')


class TutorListView(LoginRequiredMixin, generic.ListView):
    model = Person
    template_name = 'rodzina/tutor_list.html'
    fields = [
        'first_name',
        'last_name',
    ]

    def get_queryset(self):
        return Person.objects.filter(type_of_person='T')


class PersonCreate(LoginRequiredMixin, CreateView):
    model = Person
    fields = '__all__'

    def get_success_url(self):
        if self.request.POST['type_of_person'] == 'C':
            return reverse_lazy('children')
        else:
            return reverse_lazy('tutor')


class PersonUpdate(LoginRequiredMixin, UpdateView):
    model = Person
    fields = [
        'first_name',
        'last_name',
        'type_of_person',
        'family',
        'group',
    ]

    def get_success_url(self):
        if self.request.POST['type_of_person'] == 'C':
            return reverse_lazy('children')
        else:
            return reverse_lazy('tutor')


class PersonJSON(LoginRequiredMixin, SingleObjectMixin, View):
    model = Person

    def get(self, *args, **kwargs):
        self.object = [self.get_object()]
        data = serializers.serialize("json", self.object)
        return JsonResponse(data, safe=False)

    def post(self, request, *args, **kwargs):
        person = self.get_object()
        person.first_name = self.request.POST['first_name']
        person.last_name = self.request.POST['last_name']
        person.type_of_person = self.request.POST['type_of_person']
        person.save()
        return HttpResponse(status=204)


class PersonNewAjax(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        Person.objects.create(
            first_name=self.request.POST['first_name'],
            last_name=self.request.POST['last_name'],
            type_of_person=self.request.POST['type_of_person'],
            family=Family.objects.get(pk=self.request.POST['family'])
        )
        return HttpResponse(status=204)


class PersonDeleteAjax(LoginRequiredMixin, SingleObjectMixin, View):
    model = Person

    def get(self, *args, **kwargs):
        self.object = [self.get_object()]
        data = serializers.serialize("json", self.object)
        return JsonResponse(data, safe=False)

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponse(status=204)


class FamilyListView(generic.ListView):
    model = Family


class FamilyCreate(LoginRequiredMixin, CreateView):
    model = Family
    fields = '__all__'
    template_name = 'rodzina/family_new.html'

    def get_success_url(self):
        return reverse_lazy('family_edit', args=(self.object.id,))


class FamilyUpdate(UpdateView):
    model = Family
    fields = '__all__'
    success_url = reverse_lazy('family_list')


class RFIDNewAjax(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        if not RFID.objects.filter(rfid_number=self.request.POST['rfid']):
            RFID.objects.create(
                rfid_number=self.request.POST['rfid'],
                family=Family.objects.get(pk=self.request.POST['family'])
            )
            return HttpResponse(status=204)
        message = 'Podana wartość już istnieje w bazie'
        return JsonResponse(
            status=400, data={'status': 'false', 'message': message})


class RFIDDeleteAjax(LoginRequiredMixin, SingleObjectMixin, View):
    model = RFID

    def get(self, *args, **kwargs):
        self.object = [self.get_object()]
        data = serializers.serialize("json", self.object)
        return JsonResponse(data, safe=False)

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponse(status=204)


class GroupListView(generic.ListView):
    model = Group


class GrupUpdate(UpdateView):
    model = Group
    fields = '__all__'
    success_url = reverse_lazy('group_list')

rodzina/templates/rodzina/children_list.html
{% extends "base.html" %}

{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <div class="row">
                <div class="col-md-3">
                    <h1>Lista dzieci</h1>
                </div>
                <div class="col-md-3"><a href="{% url 'person_new' %}" class="btn btn-secondary btn-warning">Dodaj
                        osobę</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Nazwisko</th>
            <th scope="col">Imie</th>
            <th scope="col">Grupa</th>
            <th scope="col">Działania</th>
        </tr>
    </thead>
    <tbody>
        {% for child in person_list %}
        <tr>
            <td>{{ child.last_name }}</td>
            <td>{{ child.first_name}}</td>
            <td>{{ child.group }}</td>

            <td>
                <div class="btn-group btn-group-sm gradient-buttonscd" role="group">

                    <a href="{% url 'person_edit' child.id %}" class="btn btn-secondary btn-success">Edytuj</a>


                    <a href="{% url 'family_edit' child.family.id %}" class="btn btn-secondary btn-success">Rodzina</a>

                    {% if child.group.id != None %}
                    <a href="{% url 'group_edit' child.group.id %}" class="btn btn-secondary btn-success">Grupa</a>
                    {% endif %}

                    <a class="btn btn-secondary btn-success">Rozliczenie</a>
                    <button type="button" class="btn-sm btn-secondary btn-danger confirm-delete" data-toggle="modal"
                        data-target="#deleteConfirm" data-id_person="{{ child.id }}">Usuń</button>
                </div>


            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>



<div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Czy usunąć osobę?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="id_person">
                <div class="personName"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="confirmButton">Potwierdź</button>
            </div>
        </div>
    </div>
</div>
{% csrf_token %}
<script>
    const csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $('#deleteConfirm').on('show.bs.modal', function (e) {
        var button = $(e.relatedTarget)
        var id_person = button.data('id_person')

        $.ajax({
            type: 'GET',
            url: '/person/' + id_person + '/delete/',
            dataType: 'json',
            success: function (data) {
                var person = JSON.parse(data)[0].fields
                $('.personName').text(person.first_name + ' ' + person.last_name)
                $('#id_person').val(id_person)

            },
            error: function () {
                $('#errors').val(`error`);
            }

        })
    })

    $('#confirmButton').on('click', function () {
        var id_person = $('#id_person').val()
        $.ajax({
            type: 'POST',
            url: '/person/' + id_person + '/delete/',
            data: {
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                action: 'post',
            },
            success: function () {
                window.location.reload(false);
            },
            error: function (xhr, errmsg, err) {
                console.log(xhr.status + ": " + xhr.responseText);
            },
        })
    })
</script>
{% endblock %}

rodzina/templates/rodzina/family_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <h1>Edycja Rodziny</h1>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<form method="POST">
    <div class="card p-5 shadow">
        <div class="form-group">
            {% csrf_token %}
            <div class="form-row mb-5">
                <div class="col">
                    {{ form.name.label_tag }}
                    {{ form.name|add_class:"form-control" }}
                </div>
                <div class="col">
                    {{ form.rfid.label_tag }}
                    {{ form.rfid|add_class:"form-control" }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </div>
    <div class="cart p5 shadow">
        <div class="card-body bg-gradient-secondary text-white">
            <h3>Członkowie rodziny</h3>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Nazwisko</th>
                    <th scope="col">Imie</th>
                    <th scope="col">Działania</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="3">
                        <h6 class="text-center">Rodzice/Opiekunowie</h6>
                    </td>
                </tr>

                {% for person in family.get_tutor %}
                <tr>
                    <td>{{ person.last_name }}</td>
                    <td>{{ person.first_name }}</td>
                    <td>
                        <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal"
                            data-target="#myModal" data-id_person="{{ person.id }}">
                            Edytuj
                        </button>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan=" 3">
                        <h6 class="text-center">Dzieci</h6>
                    </td>
                </tr>
                {% for person in family.get_children %}
                <tr>
                    <td>{{ person.last_name }}</td>
                    <td>{{ person.first_name }}</td>
                    <td>
                        <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal"
                            data-target="#myModal" data-id_person="{{ person.id }}">
                            Edytuj
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</form>
{% endblock %}

{% block modals%}
<!-- Modal -->
<form id="modal_person_update">
    {% csrf_token %}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edycja osoby</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col">
                            <label for="last_name_ajx">Nazwisko:</label>
                            <input type="text" class="form-control" id="last_name_ajx">
                        </div>
                        <div class="col">
                            <label for="first_name_ajx">Imię:</label>
                            <input type="text" class="form-control" id="first_name_ajx">
                        </div>
                    </div>
                    <div class="form-row pt-3">
                        <div class="col-6">
                            <label for="last_name_ajx">Typ osoby</label>
                            <select class="custom-select" id="type_of_person_ajx">
                                <option value="T">Opiekun</option>
                                <option value="C">Dziecko</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type='hidden' id="id_person_ajx">
                    <input type='hidden' id="id_family_ajx">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
                    <button type="button" class="btn btn-primary" id="save_button">Zapisz zmiany</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script>

</script>
{% endblock %}

rodzina/templates/rodzina/family_list.html
{% extends "base.html" %}

{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <div class="row">
                <div class="col-md-4">
                    <h1>Lista rodzin</h1>
                </div>
                <div class="col-md-3">
                    <a href="{% url 'family_new' %}" class="btn btn-secondary btn-warning">
                        Dodaj rodzinę
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Nazwa rodziny</th>
            <th scope="col">Liczba dzieci</th>
            <th scope="col">Działania</th>
        </tr>
    </thead>
    <tbody>
        {% for family in family_list %}
        <tr>
            <td>{{ family.name }}</td>
            <td>{{ family.children_count }}</td>

            <td>
                <div class="btn-group btn-group-sm gradient-buttonscd" role="group">

                    <a href="{% url 'family_edit' family.id %}" class="btn btn-secondary btn-success">Edytuj</a>

                    <a class="btn btn-secondary btn-success">Rozliczenie</a>
                </div>


            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

rodzina/templates/rodzina/family_new.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <h1>Edycja Rodziny</h1>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<form method="POST">
    <div class="card p-5 shadow">
        <div class="row">
            <div class="col-md-4">

                <div class="form-group">
                    {% csrf_token %}
                    <div class="form-row mb-5">
                        <div class="col">
                            {{ form.name.label_tag }}
                            {{ form.name|add_class:"form-control" }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Zapisz</button>
    </div>

</form>

{% endblock %}

rodzina/templates/rodzina/group_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <h1>Edycja Grupy</h1>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<div class="card p-5 shadow">
    <form method="POST">
        <div class="form-group">
            {% csrf_token %}
            <div class="form-row">
                <div class="col">
                    {{ form.name.label_tag }}
                    {{ form.name|add_class:"form-control" }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </form>
</div>
{% endblock %}

rodzina/templates/rodzina/group_form.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <h1>Edycja Grupy</h1>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<div class="card p-5 shadow">
    <form method="POST">
        <div class="form-group">
            {% csrf_token %}
            <div class="form-row mb-5">
                <div class="col">
                    {{ form.name.label_tag }}
                    {{ form.name|add_class:"form-control" }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </form>
</div>

<div class="cart p5 shadow">
    <div class="card-body bg-gradient-secondary text-white">
        <div class="row">
            <div class="col-md-4">
                <h3>Dzieci w grupie</h3>
            </div>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Nazwisko</th>
                <th scope="col">Imie</th>
            </tr>
        </thead>
        <tbody>
            {% for child in group.children.all %}
            <tr>
                <td>{{ child.last_name }}</td>
                <td>{{ child.first_name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

rodzina/templates/rodzina/group_list.html
{% extends "base.html" %}

{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <h1>Lista rodzin</h1>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Nazwa grupy</th>
            <th scope="col">Liczba dzieci</th>
            <th scope="col">Działania</th>
        </tr>
    </thead>
    <tbody>
        {% for group in group_list %}
        <tr>
            <td>{{ group.name }}</td>
            <td>{{ group.children.count }}</td>

            <td>
                <div class="btn-group btn-group-sm gradient-buttonscd" role="group">

                    <a href="{% url 'group_edit' group.id %}" class="btn btn-secondary btn-success">Edytuj</a>

                    <a class="btn btn-secondary btn-success">Rozliczenie</a>
                </div>


            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

rodzina/templates/rodzina/person_form.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <h1>Edycja osoby</h1>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<div class="card p-5 shadow">
    <form method="POST">
        <div class="form-group">
            {% csrf_token %}
            <div class="form-row">
                <div class="col">
                    {{ form.last_name.label_tag }}
                    {{ form.last_name|add_class:"form-control" }}
                </div>
                <div class="col">
                    {{ form.first_name.label_tag }}
                    {{ form.first_name|add_class:"form-control" }}
                </div>
            </div>
            <div class="form-row mt-5 mb-5">
                <div class="col">
                    {{ form.type_of_person.label_tag }}
                    {{ form.type_of_person|add_class:"form-control" }}
                </div>
                <div class="col">
                    {{ form.family.label_tag }}
                    {{ form.family|add_class:"form-control" }}
                </div>
                <div class="col">
                    {{ form.group.label_tag }}
                    {{ form.group|add_class:"form-control" }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </form>
</div>

{% endblock %}

rodzina/templates/rodzina/person_list.html
{% extends "base.html" %}

{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <h1>Lista dzieci</h1>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Nazwisko</th>
            <th scope="col">Imie</th>
            <th scope="col">Grupa</th>
            <th scope="col">Działania</th>
        </tr>
    </thead>
    <tbody>
        {% for child in person_list %}
        <tr>
            <td>{{ child.last_name }}</td>
            <td>{{ child.first_name}}</td>
            <td>{{ child.group }}</td>

            <td>
                <div class="btn-group btn-group-sm gradient-buttonscd" role="group">

                    <a href="{% url 'person_edit' child.id %}" class="btn btn-secondary btn-success">Edytuj</a>


                    <a href="{% url 'family_edit' child.family.id %}" class="btn btn-secondary btn-success">Rodzina</a>

                    {% if child.group.id != None %}
                    <a href="{% url 'group_edit' child.group.id %}" class="btn btn-secondary btn-success">Grupa</a>
                    {% endif %}

                    <a class="btn btn-secondary btn-success">Rozliczenie</a>
                </div>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

rodzina/templates/rodzina/tutor_list.html
{% extends "base.html" %}

{% block header %}

<div class="container mt-3 mb-5">
    <div class="card">
        <div class="card-body bg-gradient-primary text-white">
            <div class="row">
                <div class="col-md-4">
                    <h1>Lista opiekunów</h1>
                </div>
                <div class="col-md-3"><a href="{% url 'person_new' %}" class="btn btn-secondary btn-warning">Dodaj
                        osobę</a></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Nazwisko</th>
            <th scope="col">Imie</th>
            <th scope="col">Działania</th>
        </tr>
    </thead>
    <tbody>
        {% for tutor in person_list %}
        <tr>
            <td>{{ tutor.last_name }}</td>
            <td>{{ tutor.first_name}}</td>

            <td>
                <div class="btn-group btn-group-sm gradient-buttonscd" role="group">

                    <a href="{% url 'person_edit' tutor.id %}" class="btn btn-secondary btn-success">Edytuj</a>


                    <a href="{% url 'family_edit' tutor.family.id %}" class="btn btn-secondary btn-success">Rodzina</a>

                    <a class="btn btn-secondary btn-success">Rozliczenie</a>
                    <button type="button" class="btn-sm btn-secondary btn-danger confirm-delete" data-toggle="modal"
                        data-target="#deleteConfirm" data-id_person="{{ tutor.id }}">Usuń</button>
                </div>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog" aria-hidden="true">
    <form id="modalPerson">
        {% csrf_token %}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Czy usunąć osobę?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="id_person">
                    <div class="personName"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="confirmButton">Potwierdź</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}